from typing import Any, TYPE_CHECKING, Generic, TypeVar

if TYPE_CHECKING:
    from django.db.models.manager import Manager

T = TypeVar('T')

class QuerySet(Generic[T]):
    def as_manager(self, *args: Any, **kwargs: Any) -> 'Manager[T]': ...
    def filter(self, *args: Any, **kwargs: Any) -> 'QuerySet[T]': ...
    def order_by(self, *args: Any, **kwargs: Any) -> 'QuerySet[T]': ...
    def earliest(self, *args: Any, **kwargs: Any) -> T: ...
    def latest(self, *args: Any, **kwargs: Any) -> T: ...
    def __len__(self) -> int: ...
    def __getitem__(self, k: int) -> T: ...
