from typing import TYPE_CHECKING, Any, Union

if TYPE_CHECKING:
    from django.db.models.manager import Manager

class QuerySet:
    def as_manager(self, *args: Any, **kwargs: Any) -> Any: ...
    def filter(self, *args: Any, **kwargs: Any) -> "QuerySet": ...
    def order_by(self, *args: Any, **kwargs: Any) -> "QuerySet": ...
    def earliest(self, *args: Any, **kwargs: Any) -> Any: ...
    def latest(self, *args: Any, **kwargs: Any) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, k: Union[int, slice]) -> Any: ...
    def __iter__(self) -> Any: ...
    def __bool__(self) -> bool: ...
