class HttpResponseBase: ...
class HttpResponse(HttpResponseBase): ...
class HttpResponseRedirectBase(HttpResponse): ...
class HttpResponseRedirect(HttpResponseRedirectBase): ...
class Http404(Exception): ...
