from django.views.generic.base import ContextMixin, TemplateResponseMixin, View


class MultipleObjectMixin(ContextMixin): ...
class MultipleObjectTemplateResponseMixin(TemplateResponseMixin): ...

class BaseListView(MultipleObjectMixin, View): ...
class ListView(MultipleObjectTemplateResponseMixin, BaseListView): ...
