# Generated by Django 2.0.2 on 2018-03-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("posts", "0001_initial")]

    operations = [migrations.RenameModel(old_name="Post", new_name="Posts")]
