# Generated by Django 2.0.2 on 2018-03-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("posts", "0002_auto_20180304_2232")]

    operations = [migrations.RenameModel(old_name="Posts", new_name="Post")]
